[sdl]
output=overlay
fullscreen=false
windowresolution=original
aspect=true

[dosbox]
memsize=63

[cpu]
core=auto
cputype=auto
cycles=max

[mixer]
rate=22050
blocksize=2048
prebuffer=100

[sblaster]
sbtype=sb16
sbbase=220
irq=5
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplrate=44100
